### ISSUE TITLE
ui: implement sidebar collapsing/expansion

### ISSUE THREAD

**Issue by neSpecc** [codex-team/codex.docs#174]
1. The parent items should have arrows that could be used for the collapsing, expansion of the section

<img width="457" alt="image" src="https://user-images.githubusercontent.com/3684889/164709431-a031e279-8a52-42df-b3bd-1a25e55549a8.png">

3. The state of the section should be stored at the Local Storage 

4. Icons have their own hovers 

<img width="423" alt="image" src="https://user-images.githubusercontent.com/3684889/164709791-0ae515c8-32f3-48e7-b653-75e49ef69223.png">

Figma: https://www.figma.com/file/P3X5qbxV5DZ0cM2arsmkrP/docs?node-id=63%3A47

**Comment by nikmel2803** [comment]
done
