### ISSUE TITLE
ui: implement a search 

### ISSUE THREAD

**Issue by neSpecc** [codex-team/codex.docs#175]
1. This search should filter the sidebar items. It does not require a backend.

<img width="505" alt="image" src="https://user-images.githubusercontent.com/3684889/164710071-8a302112-b8aa-4e62-acfe-8cd8ee95d434.png">

2. Search can be focused by the shortcuts: CMD+P on Mac, CTRL+P on Windows
3. Focused input should have border and glow:

<img width="677" alt="image" src="https://user-images.githubusercontent.com/3684889/164712191-aa7366cc-830d-4af9-a818-b284ce8be3d6.png">

4. When the search input has focused, there should be an arrow navigation (Top/Down/Enter) between filtered items.

Figma: https://www.figma.com/file/P3X5qbxV5DZ0cM2arsmkrP/docs?node-id=63%3A47

**Comment by nikmel2803** [comment]
done in #215
