### ISSUE TITLE
Remove uploads path from file URL after uploading photos

### ISSUE THREAD

**Issue by nikmel2803** [codex-team/codex.docs#184]
After image uploading, we have the following responses, which contains url property with hardcoded `/uploads` path. It is bad practice and we need to remove it.

<img width="538" alt="image" src="https://user-images.githubusercontent.com/32655339/164788754-95397d70-7388-4eeb-a36c-a1e922334eee.png">

**Comment by neSpecc** [comment]
We MUST NOT store the URL at the DB. We should only store the file id instead

**Comment by neSpecc** [comment]
The converter for existed files is also required

**Comment by neSpecc** [comment]
This issue will require removing of the `url` field from the model made by the #168 PR

**Comment by nikmel2803** [comment]
done in #273
