### ISSUE TITLE
Remove config file .codexdocsrc and use the separate settings page to improve UX

### ISSUE THREAD

**Issue by talyguryn** [codex-team/codex.docs#204]
Now it is not good to use any config files for an application which should be installed easily.

I think it would be better to create a settings page with the same fields as in config file: main password, site name, menu links and any other params — and store them in "database" file as all other things.

1. For the first run we can check if required fields are empty and show the settings page without any auth.
2. User enters here all params, clicks save and asked to go to auth page (and then — to main).
3. Somewhere on the site will be places a link to settings page.

**Comment by nikmel2803** [comment]
done in #271
