### ISSUE TITLE
Wrong images' background

### ISSUE THREAD

**Issue by slaveeks** [codex-team/codex.docs#223]
![photo_2022-08-04 16 22 22](https://user-images.githubusercontent.com/81693471/182857597-5b47341b-3747-46ce-9212-0eef1d446678.jpeg)

**Comment by HyTekCoop** [comment]
I have worked on this error. I made a file describing this problem. Unfortunately it is in Russian.
[Bug with imagebackground.pdf](https://github.com/codex-team/codex.docs/files/9460804/imagebackground.pdf)

**Comment by HyTekCoop** [comment]
I updated the file and added English to the description. Please see someone for a description of this problem, because I don’t know what to do in this case, how to do it right.
[Bug with imagebackground.pdf](https://github.com/codex-team/codex.docs/files/9475925/Bug.with.imagebackground.pdf)
