### ISSUE TITLE
Make "startPage" config optional

### ISSUE THREAD

**Issue by neSpecc** [codex-team/codex.docs#232]
For now you'll see an empty page when you have no `startPage` option specified in the `.codexdocsrc`. Even you you have pages at DB.

Itstead of this, you should use the first page from the DB

![Image](https://user-images.githubusercontent.com/3684889/188494763-08878a02-6ea5-4ef3-9dd8-f0a61c1fa9db.png)

**Comment by neSpecc** [comment]
Also, there is a bug on mobile: header has an empty space for the menu even if it's not defined


![Image](https://user-images.githubusercontent.com/3684889/188494957-8fa598b8-c034-403f-b6e1-dd82ffc9165d.png)

**Comment by slaveeks** [comment]
resolved in #250
