### ISSUE TITLE
Bug: sidebar slider is hidden behind code and warning blocks

### ISSUE THREAD

**Issue by TatianaFomina** [codex-team/codex.docs#242]
![Image](https://user-images.githubusercontent.com/31101125/189130060-8662b772-8d63-4a72-8a48-1f0c7d77485f.png)

**Comment by TatianaFomina** [comment]
> It's a rare case, isn't it?

not quite rare, it can be reproduced on screens with width from 1050px to 1425px

**Comment by neSpecc** [comment]
So it requires the UI solution first. Anyway, fixing z-index looks reasonable
