### ISSUE TITLE
Bug: no space between last edit label and breadcrumbs

### ISSUE THREAD

**Issue by TatianaFomina** [codex-team/codex.docs#253]
![Image](https://user-images.githubusercontent.com/31101125/189545383-28ee8e7c-5850-4db4-b9d4-f8ce5490bde2.png)

**Comment by neSpecc** [comment]
Seems like the problem caused by a collapsed content block. Are you testing the latest version?

**Comment by TatianaFomina** [comment]
probably not.... doesn't demo stage contain the latest version?

**Comment by TatianaFomina** [comment]
can not be reproduced in branch main
