### ISSUE TITLE
Add "Copy" button to the "Code" block

### ISSUE THREAD

**Issue by makarbass** [codex-team/codex.docs#270]
Button for copying block content

like:
![image](https://user-images.githubusercontent.com/52400119/191001211-24e2ec22-da57-4eca-bdca-14f915e9e34d.png)

**Comment by lionep** [comment]
It seems to be implemented no ?

<img width="716" alt="image" src="https://user-images.githubusercontent.com/968319/226165869-356bd258-8b39-4f7e-bf6a-a14f6e220374.png">

**Comment by neSpecc** [comment]
Seems implemented by @alsolovyev
