### ISSUE TITLE
Different sizes of side panels

### ISSUE THREAD

**Issue by alsolovyev** [codex-team/codex.docs#286]
### Description:
The sidebars ([sidebar.twig](https://github.com/codex-team/codex.docs/blob/main/src/backend/views/components/sidebar.twig), [layout-sidebar-right](https://github.com/codex-team/codex.docs/blob/main/src/backend/views/layout.twig#L30)) have different sizes although the static sizes are given for different screens ([sidebar](https://github.com/codex-team/codex.docs/blob/main/src/frontend/styles/components/sidebar.pcss#L42), [layout-sidebar-right](https://github.com/codex-team/codex.docs/blob/main/src/frontend/styles/layout.pcss#L54))

### Preview:

<details>
<summary>Sidebars Sizes</summary>

![sidebars](https://user-images.githubusercontent.com/20425619/204643898-da7d15a1-e5fb-4ce9-b12d-7f60950af192.jpg)

</details>

### Question:
Is that how it's meant to be? Do we need to prevent the right sidebar from shrinking??

**Comment by neSpecc** [comment]
For now, it is the expected behavior, but probably we need to make these two sidebars similar. Will think about it.
