### ISSUE TITLE
Question: is this repo still maintained?

### ISSUE THREAD

**Issue by mfuentesg** [codex-team/codex.docs#302]

**Comment by mfuentesg** [comment]
Hi @neSpecc 

I would like to contribute to this repo, but I'm not able to see a roadmap for this project repo more than the opened issues, is order to add capabilities to codex docs.

Thanks is advance

**Comment by neSpecc** [comment]
@mfuentesg We're designing the new product requirements and architecture at the moment.

**Comment by mfuentesg** [comment]
Hi @neSpecc production requirements are still on going?

**Comment by neSpecc** [comment]
> Hi @neSpecc production requirements are still on going?

Hey, @mfuentesg . We're currently in an active development phase. You can join if you're interested. https://codex.so/join
