### ISSUE TITLE
Login Button if not logged in

### ISSUE THREAD

**Issue by Bag72** [codex-team/codex.docs#307]
Minor issue.  If I connect up to the app and it isn't logged in I can't change the data and there appears no way to login.

I had to search to find that I can append /auth to the site URL.     That isn't obvious and not intuitive.

Could we add a Login Button when the user wasn't logged in.    It would fit in if it appeared where the New Page button is when you are logged in.

It would make it easier for new users and would look neat.

**Comment by neSpecc** [comment]
This button is needed for only a small amount of admins, but all users (readers) will see that. That's why we haven't added it to the default UI. As a workaround, you can add it to the site menu using the Config file.

**Comment by Bag72** [comment]
> As a workaround, you can add it to the site menu using the Config file.

Is there instructions for this.  I've not seen any advanced instructions for this app.

**Comment by neSpecc** [comment]
thanks, @gribanoveu

**Comment by Bag72** [comment]
@gribanoveu    Thank you.   I appreciate the help.
