### ISSUE TITLE
Raw-HTML is appended to page title 

### ISSUE THREAD

**Issue by PolinaShneider** [codex-team/codex.docs#32]
![image](https://user-images.githubusercontent.com/15448200/51912261-e7cd0700-23e4-11e9-9650-8db5ae4dc30b.png)
![image](https://user-images.githubusercontent.com/15448200/51912267-ebf92480-23e4-11e9-8bf7-a9c3608f09e6.png)

**Comment by nikmel2803** [comment]
I guess it is not relevant issue. Reopen it if necessary
