### ISSUE TITLE
Add Image Tool with uploader backend to the landing

### ISSUE THREAD

**Issue by neSpecc** [codex-team/codex.docs#41]

**Comment by talyguryn** [comment]
Решал задачу с бекендом для Image Tool. Вод код модуля, который можно просто скопировать.

https://github.com/talyguryn/codex.docs/blob/7bf8f38458424d18b01c670c52bc5d626f5b5ae0/src/routes/upload.js

Останется только подключить этот модуль в роутере:

`router.use('/', upload);`

**Comment by talyguryn** [comment]
See #42
