### ISSUE TITLE
Don't allow to leave editor if data was not saved.

### ISSUE THREAD

**Issue by neSpecc** [codex-team/codex.docs#82]
Show prompt «You really want to leave this page without saving?»

**Comment by talyguryn** [comment]
Yep. Need to handle cmd+w, tab closing or any other

**Comment by nikmel2803** [comment]
Can't reproduce issue
It is already working (checked in several browsers):
<img width="1840" alt="image" src="https://user-images.githubusercontent.com/32655339/161828938-cbbaa321-26d4-4d01-b30d-de540770a42b.png">
